# Generated by Django 2.2.6 on 2021-04-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chelp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidhelp',
            name='state',
            field=models.CharField(choices=[('Uttar Pradesh', 'Uttar Pradesh'), ('Maharastra', 'Maharastra'), ('Delhi', 'Delhi'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Haryana', 'Haryana'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Keral', 'Keral'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Rajasthan', 'Rajasthan'), ('Punjab', 'Punjab'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('West Bengal', 'West Bengal'), ('Uttarakhand', 'Uttarakhand'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Daman and Diu', 'Daman and Diu'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Ladakh', 'Ladakh'), ('Puducherry', 'Puducherry'), ('Lakshadweep', 'Lakshadweep')], max_length=100),
        ),
    ]
