# Generated by Django 2.2.6 on 2021-04-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chelp', '0002_auto_20210418_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covidhelp',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=100, null=True),
        ),
    ]
